### ISSUE TITLE
Compatibility with ES 2.0.0

### ISSUE THREAD

**Issue by benoitdechateauvieux** [elastic/elasticsearch-transport-wares#36]
The latest version of elasticsearch-transport-wares (2.7.0) is not compatible with ES 2.0.0.

```
java.lang.ClassNotFoundException: org.elasticsearch.common.settings.ImmutableSettings$Builder
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1722) ~[catalina.jar:7.0.63]
    at org.apache.catalina.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1573) ~[catalina.jar:7.0.63]
    at java.lang.Class.getDeclaredConstructors0(Native Method) ~[na:1.7.0_21]
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2413) ~[na:1.7.0_21]
    at java.lang.Class.getConstructor0(Class.java:2723) ~[na:1.7.0_21]
    at java.lang.Class.newInstance0(Class.java:345) ~[na:1.7.0_21]
    at java.lang.Class.newInstance(Class.java:327) ~[na:1.7.0_21]
    at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:116) ~[catalina.jar:7.0.63]
    at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1148) ~[catalina.jar:7.0.63]
    at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1087) ~[catalina.jar:7.0.63]
    at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5267) [catalina.jar:7.0.63]
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5557) [catalina.jar:7.0.63]
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:7.0.63]
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901) [catalina.jar:7.0.63]
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877) [catalina.jar:7.0.63]
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652) [catalina.jar:7.0.63]
    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1095) [catalina.jar:7.0.63]
    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1930) [catalina.jar:7.0.63]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_21]
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334) [na:1.7.0_21]
    at java.util.concurrent.FutureTask.run(FutureTask.java:166) [na:1.7.0_21]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_21]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_21]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_21]
```

**Comment by dadoonet** [comment]
Can you comment there? https://github.com/elastic/elasticsearch/issues/12721

**Comment by SMUnlimited** [comment]
I have submitted a fork (https://github.com/SMUnlimited/elasticsearch-transport-wares) to support building master locally for elasticsearch 2.1.0 with a simple "mvn install". 

In theory change the elasticsearch.version property and parent pom version back to 2.0.0 and that should work if you need 2.0.0 support. 

Not submitting as a pull request as I don't believe my pom changes are what elasticsearch originally intended, but useful in the mean time until/if we get an official release.

**Comment by dadoonet** [comment]
Closing. We can revisit it depending on the outcome from https://github.com/elastic/elasticsearch/issues/12721
